#!/usr/bin/php

<?php

require_once('/home/james/git/RMQ/path.inc');
require_once('/home/james/git/RMQ/get_host_info.inc');
require_once('/home/james/git/RMQ/rabbitMQLib.inc');

$stock ="AAPL";
$curl = curl_init();

curl_setopt_array($curl, [
CURLOPT_URL => "https://rapidapi.p.rapidapi.com/stock/".$stock."/book",
CURLOPT_RETURNTRANSFER => true,
CURLOPT_FOLLOWLOCATION => true,
CURLOPT_ENCODING => "",
CURLOPT_MAXREDIRS => 10,
CURLOPT_TIMEOUT => 30,
CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
CURLOPT_CUSTOMREQUEST => "GET",
CURLOPT_HTTPHEADER => [
"x-rapidapi-host: investors-exchange-iex-trading.p.rapidapi.com",
"x-rapidapi-key: 636cd705b0msh003106b728cf3e3p101c47jsn97c7c0b4b786",
"content-type: application/json"
],
]);

//$re = curl_exec($curl);
$response = json_decode(curl_exec($curl),True );


$err = curl_error($curl);

curl_close($curl);

if ($err) {
echo "cURL Error #:" . $err;
} else {

	$ticker = $response['quote']['symbol'];
	$companyName = $response['quote']['companyName'];
	$latestPrice = $response['quote']['latestPrice'];

	echo "Stock: " . $ticker . "\n" ;
	echo "Company Name: " .  $companyName . "\n";
	echo "Latest Price: " . $latestPrice . "\n";

}

$client = new rabbitMQClient("testRabbitMQ.ini" , "SQLDB");

echo "client created";

$request = array();

$request['type'] = "Data";
$request['ticker'] = $ticker;
$request['name'] =  $companyName;
$request['latestPrice'] = $latestPrice;

print_r($request);

$response = $client->send_request($request);
print_r($response);
echo "request sent";
?>
